name: shokinin20
version: 0.1.0.0
github: PilchardFriendly/cuddly-adventure
license: BSD3
author: Nick Drew
maintainer: code@nickdrew.io
copyright: 2020 Nick Drew
description: Please see the README on GitHub at <https://github.com/PilchardFriendly/cuddly-adventure#readme.md>

extra-source-files:
- Readme.md
  
dependencies:
- base >= 4.7 && < 5
- containers
- newtype
- mtl
- hedgehog
- formatting
- polysemy
- megaparsec
- ilist

default-extensions:
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
library:
  source-dirs: src
  ghc-options: -O2 -flate-specialise -fspecialise-aggressively

executables:
  shokinin20-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shokinin20

tests:
  shokinin20-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shokinin20
    - hspec
    - hspec-expectations
    # - hw-hspec-hedgehog
    # - call-stack
    - hspec-hedgehog